# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

# using nightly rustfmt options
# use: cargo +nightly fmt

group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "Vertical"
